// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3hY-G3TKK6M1jDBfTp2doDqAwQPlz8m0',
    appId: '1:1094276509436:web:b9c6dbdcbff20017177179',
    messagingSenderId: '1094276509436',
    projectId: 'derma-3fec9',
    authDomain: 'derma-3fec9.firebaseapp.com',
    storageBucket: 'derma-3fec9.firebasestorage.app',
    measurementId: 'G-SCRG0EEWR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEK16OSiJMLIRywOVJNG36m40z2TPILBM',
    appId: '1:1094276509436:android:fcb25630a735ea51177179',
    messagingSenderId: '1094276509436',
    projectId: 'derma-3fec9',
    storageBucket: 'derma-3fec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKHolyI0GkL2f6KxEYK5XANcNL1FkyEv8',
    appId: '1:1094276509436:ios:761e89b653a2558b177179',
    messagingSenderId: '1094276509436',
    projectId: 'derma-3fec9',
    storageBucket: 'derma-3fec9.firebasestorage.app',
    iosBundleId: 'com.example.skinCancerDetector',
  );
}
